import './globals.css'
// import localFont from 'next/font/local'

// const LocalFont = localFont({
//   src: '경로',
//   variable: '변수명',
//   weight: '100 900',
// })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
